### ISSUE TITLE
Core API

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/octoris#1]
**This issue may be broken down into multiples if needed**

## Tasks

- [x] Core server functionality
- [x] Hosts server on desired port
- [x] Accepts routing setup from `routeReducer`
- [x] Gives back a new promise on startup
- [x] HTTP create server
- [x] Optimized route tree navigation
- [x] Optimized startup process (Ongoing)

The core to octoris will be the primary module you get when just importing/requiring octoris like so:
```js
const octoris = required('octoris')
```

This will give you a function that accepts two parameters.

## Parameters

- `options`: `Object` - The options given to octoris
  - `options.port`: `Number` - The port number to run on
- `routes`: `Function|Object` (Not decided Yet) - These will be the collected and built out routes octoris should listen too

> There is ideas of passing a middleware array to options as well, this has not been confirmed because there is also the idea of helper functions to achieve this as well as many other things. These issues (once created) will be linked to this one at a later date

### Usage

```js
const octoris = require('octoris')
const routes = require('./routes')

octoris({ port: 8080 }, routes)
  .then(() => console.log('server started!'))
  .catch(console.error)
```
