### ISSUE TITLE
Routing API

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/octoris#2]
**As the project grows this is subject to change**
**This may be broken down into multiple smaller issues if needed**

> **Note**: `static` was renamed to `fixed` due to it being a keyword in js classes for whatever reason

## Related Issues

- #4 Request API
- #3 Response API
- #5 Methods

## Tasks

- [x] Basic Routing Method Support
- [x] Support for Accepted Methods
- [x] Route Builders
- [x] Route Reducer
- [x] Support for route params
- [x] Support for query params
- [x] Complete Radix Tree Setup
- [x] Create basic Context Object
- [x] Optimized Router Builder
- [x] Context can be re built with middleware
- [x] Catch All Route support
- [x] Route Middleware handling
- [x] 404 Handling
- [x] Reliable Error handling/feedback
- [x] Route Logging and reports
- [x] Optimized lifecycle of finding and using a route

## Description

The routing api is obviously the key piece in allowing and listening to routes the user specifies. With our completely functional approach with octoris we have a lot of ways we can approach this.

With that being said, expect this ticket to change a lot.

The router will be a separate module of functions like everything else, what functions this module contains is yet to be determined. It will look a little like this:
```js
const { route } = require('octoris/router')
```

## Usage
Following the goal of not having magic happening the function might look like so:

```js
const { route, fixed } = require('octoris/router')
const { GET, POST } = require('octoris/methods')

router([fixed('home')], [
  GET(getHandler),
  POST(postHandler)
])
```

> For more info on `octoris/methods` please see the {link issue here} methods issue

Where in the above the handlers will be route handling functions you can build out to handle when the specified route is hit with the specific method.

Regardless of how many methods a route uses even if it only has a `GET` it should still live in an Array:

```js
const { fixed, route } = require('octoris/router')
const { GET } = require('octoris/methods')

router([fixed('home')], [GET(getHandler)])
```

**Comment by dhershman1** [comment]
this is set and ready to go in the latest version of octoris
