### ISSUE TITLE
Response API

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/octoris#3]
**As per usual, things are subject to change**

## Related Issues

- #2 Routing API
- Context when an issue is created

## Tasks
**Note**: The following task list below is not fully fleshed out as more functions will probably be added at a later date

- [x] `send` response function
- [x] `json` response function
- [x] Handles status codes
- [x] Handles redirect function
- [x] Properly handle 404 responses
- [x] Optimized partial application and flow

## Description

The Response API would be in charge of working directly with Routing. It would handle all things related to building a proper response and giving it to the client.

Once again it will be a module of functions you can bring in like so:
```js
const { send } = require('octoris/response')
```

`send` won't be the only available function here, as there will be many you can use to respond properly. Each function will be granted it's own issue.

> As of right now I am unsure how I want to handle responses completely. For example status codes, would I rather attach a status code to the function? Or use a different function like `setStatus` to set a status code? 

## Usage
**The below example is simply giving the status code to the function and then the data, as mentioned above this may or may not be a thing.**

```js
const { redirect, send } = require('octoris/response')

const getHandler = ctx => {
   // Context isn't fleshed out enough yet to nail down an example
  if (!ctx.something) {
    return redirect(404, '/')
  }

  return send(200, 'You did it!')
}
```

**Comment by dhershman1** [comment]
The response API is in a good place now with handling all types of requests
