### ISSUE TITLE
HTTP Methods

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/octoris#5]
**This is subject to change as the planning continues and grows**

## Related Issues

- #2 Routing API

## Tasks

- [x] Create supported HTTP Method Functions
  - [x] Tweak these if we need each one to act just a little differently
- [x] Have methods support middleware (Possibly)
- [x] Improve flow based on above

## Methods

The methods below have been implemented with basic functionality. I am unsure if much tweaking is needed for them to do anything "particular" at this point. However clean up is recommended as currently it is just the same function with different names, I also don't like how these are handled and written out. Should for sure **revisit** this soon.

- [x] CONNECT
- [x] DELETE
- [x] GET
- [x] HEAD
- [x] OPTIONS
- [x] PATCH
- [x] POST
- [x] PUT
- [x] TRACE

## Description

The HTTP methods will be what kind of methods are allowed/able to be handled for a route They will come as functions that you will give your handler too, and then assigned to a route listener.

You can grab them from the methods module like so:

```js
const { GET, POST } = require('octoris/modules')
```

You can use destructure to grab all of the methods you want/need

## Usage

```js
const { route, static } = require('octoris/router' 
const { GET, POST } = require('octoris/methods')

// Use them directly with the route array
route([static('about')], [
  GET(getHandler),
  POST(postHandler)
])
```

**Comment by Glen-Cocoa** [comment]
While they may be behaviorally the same, the second syntax reads much more clearly, as I know exactly what is in the array (functions!)

saving the function with its handler into a variable and then passing that in an array feels like a redundant step that also makes the code less readable

**Comment by dhershman1** [comment]
This has been finished up and all methods are accounted for in their current system
